version: '3'
services:
  python:
    image: python:3.8-alpine
    working_dir: /usr/src/app
    command: |
      apk add --no-cache git
      git clone https://github.com/hexadoo/dockerpython.git
      python repo/antminer.py
